import crafttweaker.item.IItemStack;
import crafttweaker.item.IIngredient;
import crafttweaker.oredict.IOreDictEntry;
import crafttweaker.oredict.IOreDict;
mods.mekanism.chemical.infuser.addRecipe(<gas:oxygenenrichedwater>*10, <gas:nutritionalpaste> * 10, <gas:nutrientsolution>*10);
mods.mekanism.chemical.infuser.removeRecipe(<gas:oxygenenrichedwater>, <gas:nutritionalpaste> * 10, <gas:nutrientsolution>);
//感应炉
mods.thermalexpansion.InductionSmelter.removeRecipe(<thermalfoundation:material:866>, <futuremc:ancient_debris>);
mods.thermalexpansion.InductionSmelter.removeRecipe(<thermalfoundation:material:865>, <futuremc:ancient_debris>);
//gamg
/* */
mods.thermalexpansion.InductionSmelter.removeRecipe(<thermalfoundation:material:802>, <minecraft:iron_ingot>);
mods.thermalexpansion.InductionSmelter.removeRecipe(<thermalfoundation:material:768>, <minecraft:iron_ingot>);
mods.thermalexpansion.InductionSmelter.removeRecipe(<thermalfoundation:material:769>, <minecraft:iron_ingot>);
mods.thermalexpansion.InductionSmelter.removeRecipe(<thermalfoundation:material:802>, <thermalfoundation:material>);
mods.thermalexpansion.InductionSmelter.removeRecipe(<thermalfoundation:material:768>, <thermalfoundation:material>);
mods.thermalexpansion.InductionSmelter.removeRecipe(<thermalfoundation:material:769>,<thermalfoundation:material>);

//有机农场
mods.mekanism.organicfarm.removeAllRecipes();
mods.mekanism.organicfarm.removeRecipe(<minecraft:potato> * 3, <minecraft:poisonous_potato>, <minecraft:potato>, <gas:nutrientsolution>); 
mods.mekanism.organicfarm.addRecipe(<mowziesmobs:foliaath_seed>, <gas:nutrientsolution>*500, <mowziesmobs:foliaath_seed>, <mowziesmobs:foliaath_seed>, 0.15);
mods.mekanism.organicfarm.addRecipe(<mowziesmobs:foliaath_seed>, <gas:spnutrientsolutionordinary_gas>*200, <mowziesmobs:foliaath_seed>*2, <mowziesmobs:foliaath_seed>, 10.0);
mods.mekanism.organicfarm.addRecipe(<minecraft:potato>, <gas:nutrientsolution>, <minecraft:potato> * 5, <minecraft:poisonous_potato>*3, 1.0);
mods.mekanism.organicfarm.addRecipe(<harvestcraft:cornseeditem>, <gas:spnutrientsolutionordinary_gas>*200, <additions:farm-exfarm02> * 5, <harvestcraft:cornseeditem>, 1.0);
mods.mekanism.organicfarm.addRecipe(<rusticthaumaturgy:shimmerpetal_bulb>, <gas:spnutrientsolutionordinary_gas>*200, <thaumcraft:shimmerleaf> * 5, <thaumcraft:quicksilver>*1, 0.7);
mods.mekanism.organicfarm.addRecipe(<thaumicwonders:shimmerleaf_seed>, <gas:spnutrientsolutionordinary_gas>*200, <thaumcraft:shimmerleaf> * 20, <thaumcraft:quicksilver>*6, 0.7);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:tier5_inferium_seeds>, <gas:nutrientsolution>, <mysticalagriculture:crafting> * 50, <mysticalagriculture:tier5_inferium_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:tier1_inferium_seeds>, <gas:nutrientsolution>, <mysticalagriculture:crafting> * 10, <mysticalagriculture:tier1_inferium_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:electrotine_seeds>, <gas:nutrientsolution>, <mysticalagriculture:electrotine_essence> * 24, <mysticalagriculture:electrotine_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:saltpeter_seeds>, <gas:nutrientsolution>, <mysticalagriculture:saltpeter_essence> * 24, <mysticalagriculture:saltpeter_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:coralium_seeds>, <gas:nutrientsolution>, <mysticalagriculture:coralium_essence> * 24, <mysticalagriculture:coralium_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:creeper_seeds>, <gas:nutrientsolution>, <mysticalagriculture:creeper_essence> * 24, <mysticalagriculture:creeper_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:osmium_seeds>, <gas:nutrientsolution>, <mysticalagriculture:osmium_essence> * 24, <mysticalagriculture:osmium_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:pig_seeds>, <gas:nutrientsolution>, <mysticalagriculture:pig_essence> * 24, <mysticalagriculture:pig_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:silicon_seeds>, <gas:nutrientsolution>, <mysticalagriculture:silicon_essence> * 24, <mysticalagriculture:silicon_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:spider_seeds>, <gas:nutrientsolution>, <mysticalagriculture:spider_essence> * 24, <mysticalagriculture:spider_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:sapphire_seeds>, <gas:nutrientsolution>, <mysticalagriculture:sapphire_essence> * 24, <mysticalagriculture:sapphire_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:rock_crystal_seeds>, <gas:nutrientsolution>, <mysticalagriculture:rock_crystal_essence> * 24, <mysticalagriculture:rock_crystal_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:quicksilver_seeds>, <gas:nutrientsolution>, <mysticalagriculture:quicksilver_essence> * 24, <mysticalagriculture:quicksilver_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:abyssalnite_seeds>, <gas:nutrientsolution>, <mysticalagriculture:abyssalnite_essence> * 24, <mysticalagriculture:abyssalnite_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:water_seeds>, <gas:nutrientsolution>, <mysticalagriculture:water_essence> * 24, <mysticalagriculture:water_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:knightslime_seeds>, <gas:nutrientsolution>, <mysticalagriculture:knightslime_essence> * 24, <mysticalagriculture:knightslime_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:enderman_seeds>, <gas:nutrientsolution>, <mysticalagriculture:enderman_essence> * 24, <mysticalagriculture:enderman_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:stone_seeds>, <gas:nutrientsolution>, <mysticalagriculture:stone_essence> * 1, <mysticalagriculture:stone_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:guardian_seeds>, <gas:nutrientsolution>, <mysticalagriculture:guardian_essence> * 24, <mysticalagriculture:guardian_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:slime_seeds>, <gas:nutrientsolution>, <mysticalagriculture:slime_essence> * 24, <mysticalagriculture:slime_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:glowstone_seeds>, <gas:nutrientsolution>, <mysticalagriculture:glowstone_essence> * 24, <mysticalagriculture:glowstone_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:tanzanite_seeds>, <gas:nutrientsolution>, <mysticalagriculture:tanzanite_essence> * 24, <mysticalagriculture:tanzanite_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:ender_biotite_seeds>, <gas:nutrientsolution>, <mysticalagriculture:ender_biotite_essence> * 24, <mysticalagriculture:ender_biotite_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:wood_seeds>, <gas:nutrientsolution>, <mysticalagriculture:wood_essence> * 24, <mysticalagriculture:wood_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:aquamarine_seeds>, <gas:nutrientsolution>, <mysticalagriculture:aquamarine_essence> * 24, <mysticalagriculture:aquamarine_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:knightmetal_seeds>, <gas:nutrientsolution>, <mysticalagriculture:knightmetal_essence> * 24, <mysticalagriculture:knightmetal_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:aluminum_seeds>, <gas:nutrientsolution>, <mysticalagriculture:aluminum_essence> * 24, <mysticalagriculture:aluminum_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:peridot_seeds>, <gas:nutrientsolution>, <mysticalagriculture:peridot_essence> * 24, <mysticalagriculture:peridot_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:platinum_seeds>, <gas:nutrientsolution>, <mysticalagriculture:platinum_essence> * 24, <mysticalagriculture:platinum_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:blaze_seeds>, <gas:nutrientsolution>, <mysticalagriculture:blaze_essence> * 24, <mysticalagriculture:blaze_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:basalt_seeds>, <gas:nutrientsolution>, <mysticalagriculture:basalt_essence> * 24, <mysticalagriculture:basalt_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:glowstone_ingot_seeds>, <gas:nutrientsolution>, <mysticalagriculture:glowstone_ingot_essence> * 24, <mysticalagriculture:glowstone_ingot_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:ghast_seeds>, <gas:nutrientsolution>, <mysticalagriculture:ghast_essence> * 24, <mysticalagriculture:ghast_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:terrasteel_seeds>, <gas:nutrientsolution>, <mysticalagriculture:terrasteel_essence> * 24, <mysticalagriculture:terrasteel_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:marble_seeds>, <gas:nutrientsolution>, <mysticalagriculture:marble_essence> * 24, <mysticalagriculture:marble_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:zombie_seeds>, <gas:nutrientsolution>, <mysticalagriculture:zombie_essence> * 24, <mysticalagriculture:zombie_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:limestone_seeds>, <gas:nutrientsolution>, <mysticalagriculture:limestone_essence> * 24, <mysticalagriculture:limestone_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:ruby_seeds>, <gas:nutrientsolution>, <mysticalagriculture:ruby_essence> * 24, <mysticalagriculture:ruby_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:ice_seeds>, <gas:nutrientsolution>, <mysticalagriculture:ice_essence> * 24, <mysticalagriculture:ice_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:mithril_seeds>, <gas:nutrientsolution>, <mysticalagriculture:mithril_essence> * 24, <mysticalagriculture:mithril_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:steeleaf_seeds>, <gas:nutrientsolution>, <mysticalagriculture:steeleaf_essence> * 24, <mysticalagriculture:steeleaf_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:dye_seeds>, <gas:nutrientsolution>, <mysticalagriculture:dye_essence> * 24, <mysticalagriculture:dye_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:invar_seeds>, <gas:nutrientsolution>, <mysticalagriculture:invar_essence> * 24, <mysticalagriculture:invar_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:sky_stone_seeds>, <gas:nutrientsolution>, <mysticalagriculture:sky_stone_essence> * 24, <mysticalagriculture:sky_stone_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:apatite_seeds>, <gas:nutrientsolution>, <mysticalagriculture:apatite_essence> * 24, <mysticalagriculture:apatite_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:amber_seeds>, <gas:nutrientsolution>, <mysticalagriculture:amber_essence> * 24, <mysticalagriculture:amber_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:slate_seeds>, <gas:nutrientsolution>, <mysticalagriculture:slate_essence> * 24, <mysticalagriculture:slate_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:signalum_seeds>, <gas:nutrientsolution>, <mysticalagriculture:signalum_essence> * 24, <mysticalagriculture:signalum_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:manyullyn_seeds>, <gas:nutrientsolution>, <mysticalagriculture:manyullyn_essence> * 24, <mysticalagriculture:manyullyn_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:fluix_seeds>, <gas:nutrientsolution>, <mysticalagriculture:fluix_essence> * 24, <mysticalagriculture:fluix_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:brass_seeds>, <gas:nutrientsolution>, <mysticalagriculture:brass_essence> * 24, <mysticalagriculture:brass_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:ironwood_seeds>, <gas:nutrientsolution>, <mysticalagriculture:ironwood_essence> * 24, <mysticalagriculture:ironwood_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:void_metal_seeds>, <gas:nutrientsolution>, <mysticalagriculture:void_metal_essence> * 24, <mysticalagriculture:void_metal_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:refined_obsidian_seeds>, <gas:nutrientsolution>, <mysticalagriculture:refined_obsidian_essence> * 24, <mysticalagriculture:refined_obsidian_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:mystical_flower_seeds>, <gas:nutrientsolution>, <mysticalagriculture:mystical_flower_essence> * 24, <mysticalagriculture:mystical_flower_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:sulfur_seeds>, <gas:nutrientsolution>, <mysticalagriculture:sulfur_essence> * 24, <mysticalagriculture:sulfur_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:starmetal_seeds>, <gas:nutrientsolution>, <mysticalagriculture:starmetal_essence> * 24, <mysticalagriculture:starmetal_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:dirt_seeds>, <gas:nutrientsolution>, <mysticalagriculture:dirt_essence> * 24, <mysticalagriculture:dirt_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:alumite_seeds>, <gas:nutrientsolution>, <mysticalagriculture:alumite_essence> * 24, <mysticalagriculture:alumite_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:rabbit_seeds>, <gas:nutrientsolution>, <mysticalagriculture:rabbit_essence> * 24, <mysticalagriculture:rabbit_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:iridium_seeds>, <gas:nutrientsolution>, <mysticalagriculture:iridium_essence> * 24, <mysticalagriculture:iridium_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:lumium_seeds>, <gas:nutrientsolution>, <mysticalagriculture:lumium_essence> * 24, <mysticalagriculture:lumium_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:malachite_seeds>, <gas:nutrientsolution>, <mysticalagriculture:malachite_essence> * 24, <mysticalagriculture:malachite_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:manasteel_seeds>, <gas:nutrientsolution>, <mysticalagriculture:manasteel_essence> * 24, <mysticalagriculture:manasteel_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:sheep_seeds>, <gas:nutrientsolution>, <mysticalagriculture:sheep_essence> * 24, <mysticalagriculture:sheep_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:cow_seeds>, <gas:nutrientsolution>, <mysticalagriculture:cow_essence> * 24, <mysticalagriculture:cow_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:steel_seeds>, <gas:nutrientsolution>, <mysticalagriculture:steel_essence> * 24, <mysticalagriculture:steel_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:blizz_seeds>, <gas:nutrientsolution>, <mysticalagriculture:blizz_essence> * 24, <mysticalagriculture:blizz_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:fire_seeds>, <gas:nutrientsolution>, <mysticalagriculture:fire_essence> * 24, <mysticalagriculture:fire_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:draconium_seeds>, <gas:nutrientsolution>, <mysticalagriculture:draconium_essence> * 24, <mysticalagriculture:draconium_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:constantan_seeds>, <gas:nutrientsolution>, <mysticalagriculture:constantan_essence> * 24, <mysticalagriculture:constantan_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:nether_seeds>, <gas:nutrientsolution>, <mysticalagriculture:nether_essence> * 24, <mysticalagriculture:nether_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:electrum_seeds>, <gas:nutrientsolution>, <mysticalagriculture:electrum_essence> * 24, <mysticalagriculture:electrum_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:black_quartz_seeds>, <gas:nutrientsolution>, <mysticalagriculture:black_quartz_essence> * 24, <mysticalagriculture:black_quartz_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagradditions:neutronium_seeds>, <gas:nutrientsolution>, <mysticalagradditions:neutronium_essence> * 4, <mysticalagradditions:neutronium_seeds> * 1, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagradditions:nether_star_seeds>, <gas:nutrientsolution>, <mysticalagradditions:nether_star_essence> * 4, <mysticalagradditions:nether_star_seeds> * 1, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:nature_seeds>, <gas:nutrientsolution>, <mysticalagriculture:nature_essence> * 24, <mysticalagriculture:nature_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:certus_quartz_seeds>, <gas:nutrientsolution>, <mysticalagriculture:certus_quartz_essence> * 24, <mysticalagriculture:certus_quartz_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagriculture:thaumium_seeds>, <gas:nutrientsolution>, <mysticalagriculture:thaumium_essence> * 24,<mysticalagriculture:thaumium_seeds> * 4, 1.0);
mods.mekanism.organicfarm.addRecipe(<mysticalagradditions:dragon_egg_seeds>, <gas:nutrientsolution>, <mysticalagradditions:dragon_egg_essence> * 4,<mysticalagradditions:dragon_egg_seeds> * 1, 1.0);

//毒马铃薯
mods.mekanism.organicfarm.addRecipe(<minecraft:poisonous_potato>, <gas:spnutrientsolutionordinary_gas>*50, <extrabotany:material:2>*1, <minecraft:poisonous_potato>*64, 1.0);
//化学溶解室
mods.mekanism.chemical.dissolution.addRecipe(<ore:listAllveggie>*64, <gas:nutritionalpaste> * 6500);
mods.mekanism.chemical.dissolution.addRecipe(<additions:farm-exfarm02>*64, <gas:nutritionalpaste> * 15500);
//熔炉
furnace.addRecipe(<minecraft:coal:1>, <ore:logWood>);
furnace.addRecipe(<thaumadditions:mithrillium_ingot>, <ore:spdustMithrillium>);
furnace.addRecipe(<thaumadditions:mithminite_ingot>, <ore:spdustMithminite>);
furnace.addRecipe(<thaumadditions:adaminite_ingot>, <ore:spdustAdaminite>);     
furnace.addRecipe(<extrabotany:material:1>, <ore:spdustOrichalcos>);
furnace.addRecipe(<additions:fxt-tz>, <ore:spdustTz>);   
furnace.addRecipe(<additions:fxt-auric>, <ore:spdustSjy>);  
furnace.addRecipe(<additions:fxt-xy>, <ore:spdustYlx>);  
furnace.addRecipe(<additions:fxt-fantastic_feather>, <ore:spdustFf>); 
furnace.addRecipe(<tconevo:metal:5>, <ore:spdustDraconicmetal>); 
furnace.addRecipe(<additions:fxt-bx_ingot>, <ore:spdustBx>); 
furnace.addRecipe(<tconevo:metal:10>, <ore:spdustChaoticmetal>); 
furnace.addRecipe(<avaritia:resource:5>, <ore:spdustInfinity>); 
furnace.addRecipe(<additions:fxt-nmp_tree>, <ore:spdustBaddream>); 
furnace.addRecipe(<futuremc:netherite_scrap>, <ore:spdustNetherite>); 
furnace.addRecipe(<tconevo:metal:20>, <ore:spdustPrimordial>); 
furnace.addRecipe(<beto:worldtitaniu>, <ore:spdustWorldtitaniu>); 
furnace.addRecipe(<thaumictinkerer:kamiresource:2>*8, <ore:spdustIchorium>); 
furnace.addRecipe(<additions:farm-meksteel>, <additions:farm-meksteelfen>); 
furnace.addRecipe(<additions:farm-mekiron>,<mekanism:dust>);
furnace.addRecipe(<tcomplement:materials:1>,<additions:fxt-nether_grout>);
furnace.addRecipe(<coffeework:cake_sponge>,<additions:delight-cakepi>);
furnace.addRecipe(<additions:delight-cooked_boar>,<additions:delight-wild_boar>);
furnace.addRecipe(<additions:delight-cook_goat_meat>,<additions:delight-goat_meat>);
furnace.addRecipe(<minecraft:bread>,<additions:delight-wheat_dough>);
furnace.addRecipe(<additions:delight-cassava_bread>,<additions:delight-cassava_dough>);

furnace.remove(<tconstruct:seared:4>);
furnace.remove(<tcomplement:scorched_block>);
furnace.remove(<tcomplement:scorched_block:4>);
//妙妙工具
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds/aer>, <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"aer"})*10, <thaumadditions:vis_seeds/aer>, 1.0);  
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds/alienis>, <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"alienis"})*10, <thaumadditions:vis_seeds/alienis>, 1.0);  
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds/alkimia>, <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"alkimia"})*10, <thaumadditions:vis_seeds/alkimia>, 1.0);  
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds/aqua>, <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"aqua"})*10, <thaumadditions:vis_seeds/aqua>, 1.0);  
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds/auram>, <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"auram"})*10,<thaumadditions:vis_seeds/auram>, 1.0);  
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds/aversio>, <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"aversio"})*10, <thaumadditions:vis_seeds/aversio>, 1.0);  
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds/bestia>, <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"bestia"})*10, <thaumadditions:vis_seeds/bestia>, 1.0);  
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds/cognitio>, <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"cognitio"})*10, <thaumadditions:vis_seeds/cognitio>, 1.0);  
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds/desiderium>, <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"desiderium"})*10, <thaumadditions:vis_seeds/desiderium>, 1.0);  
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds/draco>, <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"draco"})*10, <thaumadditions:vis_seeds/draco>, 1.0);  
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds/exanimis>, <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"exanimis"})*10,<thaumadditions:vis_seeds/exanimis>, 1.0);  
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds/exitium>, <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"exitium"})*10, <thaumadditions:vis_seeds/exitium>, 1.0);   
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds/fabrico>, <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"fabrico"})*10, <thaumadditions:vis_seeds/fabrico>, 1.0);   
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds/fluctus>, <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"fluctus"})*10,<thaumadditions:vis_seeds/fluctus>, 1.0);  
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds/gelum>, <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"gelum"})*10, <thaumadditions:vis_seeds/gelum>, 1.0);  
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds/herba>, <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"herba"})*10, <thaumadditions:vis_seeds/herba>, 1.0);    
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds/humanus>, <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"humanus"})*10, <thaumadditions:vis_seeds/humanus>, 1.0);  
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds/ignis>, <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"ignis"})*10, <thaumadditions:vis_seeds/ignis>, 1.0);   
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds/imperium>, <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"imperium"})*10, <thaumadditions:vis_seeds/imperium>, 1.0);    
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds/infernum>, <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"infernum"})*10, <thaumadditions:vis_seeds/infernum>, 1.0);  
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds/instrumentum>, <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"instrumentum"})*10, <thaumadditions:vis_seeds/instrumentum>, 1.0);   
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds/lux>, <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"lux"})*10, <thaumadditions:vis_seeds/lux>, 1.0);   
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds/machina>, <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"machina"})*10, <thaumadditions:vis_seeds/machina>, 1.0);  
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds/metallum>, <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"metallum"})*10, <thaumadditions:vis_seeds/metallum>, 1.0);  
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds/mortuus>, <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"mortuus"})*10, <thaumadditions:vis_seeds/mortuus>, 1.0);   
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds/motus>, <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"motus"})*10, <thaumadditions:vis_seeds/motus>, 1.0);  
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds/ordo>, <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"ordo"})*10, <thaumadditions:vis_seeds/ordo>, 1.0);  
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds/perditio>, <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"perditio"})*10, <thaumadditions:vis_seeds/perditio>, 1.0);   
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds/permutatio>, <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"permutatio"})*10, <thaumadditions:vis_seeds/permutatio>, 1.0);  
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds/potentia>, <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"potentia"})*10, <thaumadditions:vis_seeds/potentia>, 1.0);  
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds/praecantatio>, <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"praecantatio"})*10, <thaumadditions:vis_seeds/praecantatio>, 1.0);  
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds/praemunio>, <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"praemunio"})*10, <thaumadditions:vis_seeds/praemunio>, 1.0);   
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds/rattus>, <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"rattus"})*10, <thaumadditions:vis_seeds/rattus>, 1.0);  
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds/sensus>, <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"sensus"})*10, <thaumadditions:vis_seeds/sensus>, 1.0);  
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds/sonus>, <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"sonus"})*10, <thaumadditions:vis_seeds/sonus>, 1.0);   
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds/spiritus>, <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"spiritus"})*10, <thaumadditions:vis_seeds/spiritus>, 1.0);  
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds/tenebrae>, <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"tenebrae"})*10, <thaumadditions:vis_seeds/tenebrae>, 1.0);  
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds/terra>, <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"terra"})*10, <thaumadditions:vis_seeds/terra>, 1.0);  
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds/vacuos>, <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"vacuos"})*10,<thaumadditions:vis_seeds/vacuos>, 1.0);  
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds/ventus>, <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"ventus"})*10,<thaumadditions:vis_seeds/ventus>, 1.0);  
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds/victus>, <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"victus"})*10,<thaumadditions:vis_seeds/victus>, 1.0);  
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds/vinculum>, <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"vinculum"})*10, <thaumadditions:vis_seeds/vinculum>, 1.0);  
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds/visum>, <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"visum"})*10,<thaumadditions:vis_seeds/visum>, 1.0);  
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds/vitium>, <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"vitium"})*10,<thaumadditions:vis_seeds/vitium>, 1.0);  
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds/vitreus>, <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"vitreus"})*10, <thaumadditions:vis_seeds/vitreus>, 1.0);   
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds/volatus>, <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"volatus"})*10, <thaumadditions:vis_seeds/volatus>, 1.0);  
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds>.withTag({Aspect: "coralos"}), <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"coralos"})*10, <thaumadditions:vis_seeds>.withTag({Aspect: "coralos"}), 1.0);  
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds>.withTag({Aspect: "desidia"}), <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"desidia"})*10, <thaumadditions:vis_seeds>.withTag({Aspect: "desidia"}), 1.0);  
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds>.withTag({Aspect: "dreadia"}), <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"dreadia"})*10, <thaumadditions:vis_seeds>.withTag({Aspect: "dreadia"}), 1.0);  
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds>.withTag({Aspect: "gula"}), <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"gula"})*10, <thaumadditions:vis_seeds>.withTag({Aspect: "gula"}), 1.0);  
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds>.withTag({Aspect: "infernus"}), <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"infernus"})*10, <thaumadditions:vis_seeds>.withTag({Aspect: "infernus"}), 1.0);  
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds>.withTag({Aspect: "invidia"}), <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"invidia"})*10, <thaumadditions:vis_seeds>.withTag({Aspect: "invidia"}), 1.0);  
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds>.withTag({Aspect: "ira"}), <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"ira"})*10, <thaumadditions:vis_seeds>.withTag({Aspect: "ira"}), 1.0);  
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds>.withTag({Aspect: "luxuria"}), <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"luxuria"})*10, <thaumadditions:vis_seeds>.withTag({Aspect: "luxuria"}), 1.0);  
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds>.withTag({Aspect: "mythus"}), <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"mythus"})*10, <thaumadditions:vis_seeds>.withTag({Aspect: "mythus"}), 1.0);  
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds>.withTag({Aspect: "tinctura"}), <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"tinctura"})*10, <thaumadditions:vis_seeds>.withTag({Aspect: "tinctura"}), 1.0);  
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds>.withTag({Aspect: "tempus"}), <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"tempus"})*10, <thaumadditions:vis_seeds>.withTag({Aspect: "tempus"}), 1.0);  
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds>.withTag({Aspect: "superbia"}), <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"superbia"})*10, <thaumadditions:vis_seeds>.withTag({Aspect: "superbia"}), 1.0); 
mods.mekanism.organicfarm.addRecipe(<thaumadditions:vis_seeds>.withTag({Aspect: "spatio"}), <gas:visnutrientsolutionordinary_gas>*500, <thaumadditions:vis_pod>.withTag({Aspect:"spatio"})*10, <thaumadditions:vis_seeds>.withTag({Aspect: "spatio"}), 1.0);  
